alg_name: 'DINM'
model_name: "./hugging_cache/llama-2-7b"  # the vanilla LLM path  
model_class: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
device: 0

suffix_system_prompt: "If the user's request is reasonable, give the correct answer. Please give the right response:"

# You can specify the edited layer for all data in advance, for example: layer: [31]
# DINM locates the toxic layer for each instance in safety_editour.py
layers: []
num_steps: 10
batch_size: 1
max_length: 1000
max_output_length: 600
lr: 5e-4
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: True
